# Generated by Django 3.1.3 on 2023-03-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('country', models.TextField()),
                ('birth', models.TextField()),
                ('age', models.TextField(blank=True)),
                ('club', models.TextField()),
                ('position', models.TextField(blank=True)),
                ('nickname', models.TextField(blank=True)),
                ('height', models.TextField(blank=True)),
                ('weight', models.TextField(blank=True)),
                ('Njersey', models.TextField(blank=True)),
            ],
        ),
    ]
