# Generated by Django 3.1.3 on 2023-03-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='Njersey',
            new_name='jersey',
        ),
    ]
