# Generated by Django 3.1.3 on 2023-05-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_auto_20230309_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
